### ISSUE TITLE
Yarn を利用した立ち上げに失敗する。

### ISSUE THREAD

**Issue by dorimiamn** [nnn-training/faq#40]
```
yarn dev
```
を実行したところ以下のようなエラーを吐く。
```
yarn run v1.22.19
$ next
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
warn  - Minimum recommended TypeScript version is v4.3.2, older versions can potentially be incompatible with Next.js. Detected: 4.0.8
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (/Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack/bundle5.js:133863:18)
    at BulkUpdateDecorator.update (/Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack/bundle5.js:133764:50)
    at OriginalSource.updateHash (/Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack-sources2/index.js:1:21039)
    at NormalModule._initBuildHash (/Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack/bundle5.js:65771:17)
    at handleParseResult (/Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack/bundle5.js:65837:10)
    at /Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack/bundle5.js:65929:4
    at processResult (/Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack/bundle5.js:65646:11)
    at /Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack/bundle5.js:65710:5
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (/Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack/bundle5.js:133863:18)
    at BulkUpdateDecorator.update (/Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack/bundle5.js:133764:50)
    at OriginalSource.updateHash (/Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack-sources2/index.js:1:21039)
    at NormalModule._initBuildHash (/Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack/bundle5.js:65771:17)
    at handleParseResult (/Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack/bundle5.js:65837:10)
    at /Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack/bundle5.js:65929:4
    at processResult (/Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack/bundle5.js:65646:11)
    at /Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack/bundle5.js:65710:5
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (/Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack/bundle5.js:133863:18)
    at BulkUpdateDecorator.update (/Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack/bundle5.js:133764:50)
    at OriginalSource.updateHash (/Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack-sources2/index.js:1:21039)
    at NormalModule._initBuildHash (/Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack/bundle5.js:65771:17)
    at handleParseResult (/Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack/bundle5.js:65837:10)
    at /Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack/bundle5.js:65929:4
    at processResult (/Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack/bundle5.js:65646:11)
    at /Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack/bundle5.js:65710:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
shunsuke_midorikawa@smidorikawa faq % yarn install
yarn install v1.22.19
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.24s.
shunsuke_midorikawa@smidorikawa faq % yarn dev
yarn run v1.22.19
$ next
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
warn  - Minimum recommended TypeScript version is v4.3.2, older versions can potentially be incompatible with Next.js. Detected: 4.0.8
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (/Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack/bundle5.js:133863:18)
    at BulkUpdateDecorator.update (/Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack/bundle5.js:133764:50)
    at OriginalSource.updateHash (/Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack-sources2/index.js:1:21039)
    at NormalModule._initBuildHash (/Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack/bundle5.js:65771:17)
    at handleParseResult (/Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack/bundle5.js:65837:10)
    at /Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack/bundle5.js:65929:4
    at processResult (/Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack/bundle5.js:65646:11)
    at /Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack/bundle5.js:65710:5
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (/Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack/bundle5.js:133863:18)
    at BulkUpdateDecorator.update (/Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack/bundle5.js:133764:50)
    at OriginalSource.updateHash (/Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack-sources2/index.js:1:21039)
    at NormalModule._initBuildHash (/Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack/bundle5.js:65771:17)
    at handleParseResult (/Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack/bundle5.js:65837:10)
    at /Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack/bundle5.js:65929:4
    at processResult (/Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack/bundle5.js:65646:11)
    at /Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack/bundle5.js:65710:5
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (/Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack/bundle5.js:133863:18)
    at BulkUpdateDecorator.update (/Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack/bundle5.js:133764:50)
    at OriginalSource.updateHash (/Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack-sources2/index.js:1:21039)
    at NormalModule._initBuildHash (/Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack/bundle5.js:65771:17)
    at handleParseResult (/Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack/bundle5.js:65837:10)
    at /Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack/bundle5.js:65929:4
    at processResult (/Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack/bundle5.js:65646:11)
    at /Users/shunsuke_midorikawa/workspace/faq/node_modules/next/dist/compiled/webpack/bundle5.js:65710:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by mikrogeophagus** [comment]
根本的な解決策ではないと思いますが、Node.js のバージョンを 16 以下に下げると、ひとまず立ち上げることはできました。原因や対処法は下記の記事が詳しそうです。

https://sebhastian.com/error-0308010c-digital-envelope-routines-unsupported/

**Comment by mikrogeophagus** [comment]
Node.js v18 の場合は、`NODE_OPTIONS=--openssl-legacy-provider yarn dev` が使えそうです。

**Comment by dorimiamn** [comment]
あー、Node.js のバージョンでエラー出るんですね。そこも指定されるものだと考えていました。

試してみます。
ありがとうございます！

**Comment by dorimiamn** [comment]
無事動きました！

**Comment by mikrogeophagus** [comment]
よかったです！🎉

**Comment by dorimiamn** [comment]
気になるので根本的な解決を行いたいんですが
根本的な解決手段としては
-package.json にengines を追加してNode.js のバージョンを指定
- Webpack のバージョンを更新
という形ですかね。

前者はそもそも根本的とは言わないかもしれません？

全体的に更新を予定されているならば頑張って後者の方をやったほうがいいと思うので、自分に手に負えるかわかりませんが試しにやってみたいです！

**Comment by mikrogeophagus** [comment]
根本的に解決できると嬉しいですね！
ただ、もし Next.js の Webpack の問題だとすると厄介そうです。😖

**Comment by dorimiamn** [comment]
最新のNext.js が v13 なのに対して手元のNext.js のバージョンを確認したら v11.0.1 だったので私がなんか失敗してるかもしれません。
package.json みたらNext.js の指定はlatestって書いてあるので最新バージョンが入るものだと思っていたのですが…。

**Comment by mikrogeophagus** [comment]
私の手元でも v11.0.1 の Next.js でした。
このバージョンの Next.js が使っている Webpack は v4.44.1 でした。

**Comment by dorimiamn** [comment]
Next.js v11 がReact の最小バージョンとしてv17.0.2 を指定してることがlatest のバージョンを下げる原因になっているのかも？

**Comment by dorimiamn** [comment]
自分起因の問題じゃなさそうで安心しました！
そうなると、Next.jsのバージョンを上げることから考えて行った方が良さそうですね。

**Comment by mikrogeophagus** [comment]
そうですね！こちらも明示的にバージョンを指定した方がよさそうですね。
https://github.com/nnn-training/faq/blob/93725070a2881105ab748ee0d51d21cf245f5c8f/package.json#L19
